### ISSUE TITLE
Unable to deal with a fullchain certificate PEM

### ISSUE THREAD

**Issue by kelson42** [dsully/perl-crypt-openssl-pkcs12#22]
## Description

If the first argument of `create()` is the certificate with its full trust chain, then the chain is ignored. Only the leaf certificate is in the p12.

### Expected behaviour

The trust chain should be included (like the `openssl` command line does.

### Actual behaviour

The trust chain is skipped.

## Operating system and version

Crypt-OpenSSL-PKCS12-0.8 with OpenSSL 1.0.1f 6 Jan 2014

## Perl version

perl5 (revision 5 version 24 subversion 1)

## Remark

Looks quite normal, as `NULL` is given as `ca` list of certificates here https://github.com/dsully/perl-crypt-openssl-pkcs12/blob/master/PKCS12.xs#L455

**Comment by jonasbn** [comment]
Hi @kelson42 this seems to be fixed with PR #27 also as far as I can understand the code and the use of OpenSSL's `pkcs12_create` routine - please advice

**Comment by kelson42** [comment]
@jonasbn yes. Thank you for the review and merge.
