### ISSUE TITLE
included Module::Install is conflicting

### ISSUE THREAD

**Issue by Tux** [dsully/perl-crypt-openssl-pkcs12#3]
.cpan/build/Crypt-OpenSSL-PKCS12-0.6-ejy4my 524 > perl Makefile.PL
Unknown function is found at Makefile.PL line 17.
Execution of Makefile.PL aborted due to runtime errors.

If you're a contributor to a project, you may need to install
some Module::Install extensions from CPAN (or other repository).
If you're a user of a module, please contact the author.

That would be requires_external_cc (), which is in Module::Install::External, which is not in your inc/

_my_ Module::Install::External is 1.06

**Comment by blackprojects** [comment]
still exists ...

**Comment by jonasbn** [comment]
I had to add External.pm to the MANIFEST file for distribution. Please see: PR: #13 

jonasbn

**Comment by jonasbn** [comment]
This have been addressed, a new release should demonstrate this.

**Comment by jonasbn** [comment]
@dsully this issue has been addressed and it can be closed :-)
