### ISSUE TITLE
MYMETA must not be included

### ISSUE THREAD

**Issue by chorny** [dsully/perl-crypt-openssl-pkcs12#32]
Your distribution (JONASBN/Crypt-OpenSSL-PKCS12-1.1.tar.gz) contains files MYMETA.json/MYMETA.yml. These files must not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is for an old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=JONASBN and contact me.
P.P.S. This report was generated automatically.

**Comment by jonasbn** [comment]
Hi @chorny 

I have just uploaded a maintenance release 1.2, thanks for the bug report. I hope my patch fixes the issue you spotted.

Have a nice weekend

jonasbn
