### ISSUE TITLE
Make test fails on windows?

### ISSUE THREAD

**Issue by sectokia** [dsully/perl-crypt-openssl-pkcs12#33]
# Issue Template

## Description

Fails make test

### Expected behaviour

Pass make test

### Actual behaviour

Fails make test 

## Operating system and version

_Please provide version on the operating system etc. used._

### Windows (pre version 7)

Microsoft Windows [Version 10.0.17134.950]

_For information on the specific distribution. Please consult your distribution documentation._

## Crypt::OpenSSL::PKCS12 version

Latest on CPAN (Module version: 1.2)

## Perl version

_Please provide version on the Perl version used._

perl5 (revision 5 version 30 subversion 0)

## OpenSSL version

_Please provide version on the OpenSSL version used._

perl5 (revision 5 version 30 subversion 0)

## Output, if available

`Running make test for JONASBN/Crypt-OpenSSL-PKCS12-1.2.tar.gz
"C:\Strawberry\perl\bin\perl.exe" "-Iinc" -MExtUtils::Command::MM -e cp_nonempty -- PKCS12.bs blib\arch\auto\Crypt\OpenSSL\PKCS12\PKCS12.bs 644
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib\lib', 'blib\arch')" t/pkcs12.t t/pod-coverage.t t/pod.t
t/pkcs12.t ........ 1/13 ¦Öþ: Couldn't create PKCS12 from d2i_PKCS12_BIO(): 7948:error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data:crypto/asn1/a_d2i_fp.c:198:
# Looks like your test exited with 255 just after 1.
t/pkcs12.t ........ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 12/13 subtests
t/pod-coverage.t .. ok
t/pod.t ........... ok

Test Summary Report
-------------------
t/pkcs12.t      (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 13 tests but ran 1.
Files=3, Tests=3,  2 wallclock secs ( 0.03 usr +  0.03 sys =  0.06 CPU)
Result: FAIL
Failed 1/3 test programs. 0/3 subtests failed.
gmake: *** [Makefile:970: test_dynamic] Error 255
  JONASBN/Crypt-OpenSSL-PKCS12-1.2.tar.gz
  C:\STRAWB~1\c\bin\gmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports JONASBN/Crypt-OpenSSL-PKCS12-1.2.tar.gz
Stopping: 'install' failed for 'Crypt::OpenSSL::PKCS12'.
Failed during this command:
 JONASBN/Crypt-OpenSSL-PKCS12-1.2.tar.gz      : make_test NO`

## Step by step guide to reproducing the issue

CPAN
install Crypt::OpenSSL::PKCS12

**Comment by SmartCodeMaker** [comment]
@sectokia @jonasbn I can't see full test output, but the patch e317a13 may solve it. To see full test output, we can use
`make test TEST_VERBOSE=1` (or `gmake test TEST_VERBOSE=1`). Also, `prove --verbose` running from the project root directory will do the same.

**Comment by jonasbn** [comment]
@SmartCodeMaker I am with you on this, this might be the needed fix. I do not have a Windows environment for Perl development. The GitHub Actions seem to prove that is works, would be nice with a confirmation from @sectokia or somebody with access to a Windows environment.

**Comment by jonasbn** [comment]
Hi @sectokia 

I am closing this issue, since the new CI integrations demonstrate successful builds on Windows. Unfortunately the CPAN testers website does not really reply with data where I would be able to assert the newest release.

Thank you for your issue report
