### ISSUE TITLE
Investigate reports on failing tests from CPAN testers; 1.92 (OpenBSD)

### ISSUE THREAD

**Issue by jonasbn** [dsully/perl-crypt-openssl-pkcs12#48]
Investigate reports on failing tests from CPAN testers. Seems to be OpenBSD issues.

Crypt-OpenSSL-PKCS12-1.92:

- OpenBSD.amd64-openbsd / 5.38.0:
  - FAIL http://www.cpantesters.org/cpan/report/f41dbe04-72f9-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.38.2:
  - FAIL http://www.cpantesters.org/cpan/report/633b5b36-727b-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.38.2:
  - FAIL http://www.cpantesters.org/cpan/report/f5687540-72ba-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.10.0:
  - FAIL http://www.cpantesters.org/cpan/report/52052060-7189-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.40.0:
  - FAIL http://www.cpantesters.org/cpan/report/5f108be4-71f4-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.8.9:
  - FAIL http://www.cpantesters.org/cpan/report/957a7858-71b2-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.10.0:
  - FAIL http://www.cpantesters.org/cpan/report/d2e54c0a-71a2-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.40.0:
  - FAIL http://www.cpantesters.org/cpan/report/69a98b6a-7239-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.8.9:
  - FAIL http://www.cpantesters.org/cpan/report/cb6aaa0e-71c2-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.10.1:
  - FAIL http://www.cpantesters.org/cpan/report/7193bc3e-7152-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.0:
  - FAIL http://www.cpantesters.org/cpan/report/583e9d9c-710e-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.1:
  - FAIL http://www.cpantesters.org/cpan/report/b02784fa-70bf-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.10.1:
  - FAIL http://www.cpantesters.org/cpan/report/24a6eb98-716c-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.0:
  - FAIL http://www.cpantesters.org/cpan/report/16fd9c74-7132-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.1:
  - FAIL http://www.cpantesters.org/cpan/report/45db1a14-70ea-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.2:
  - FAIL http://www.cpantesters.org/cpan/report/d6fdecdc-706e-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.3:
  - FAIL http://www.cpantesters.org/cpan/report/84c0c282-701e-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.2:
  - FAIL http://www.cpantesters.org/cpan/report/170554e2-709b-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.3:
  - FAIL http://www.cpantesters.org/cpan/report/97b6c302-7049-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.4:
  - FAIL http://www.cpantesters.org/cpan/report/a903b412-6ff9-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.4:
  - FAIL http://www.cpantesters.org/cpan/report/fc7d38f8-6fd0-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.12.5:
  - FAIL http://www.cpantesters.org/cpan/report/2da8396e-6f81-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.14.0:
  - FAIL http://www.cpantesters.org/cpan/report/afd27b52-6f22-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.12.5:
  - FAIL http://www.cpantesters.org/cpan/report/63bb2f34-6fa9-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd-thread-multi / 5.14.0:
  - FAIL http://www.cpantesters.org/cpan/report/490940f4-6f59-11ef-98b0-b3c3213a625c 

- OpenBSD.amd64-openbsd / 5.14.1:
  - FAIL http://www.cpantesters.org/cpan/report/ccaac62e-6eb6-11ef-98b0-b3c3213a625c

- OpenBSD.amd64-openbsd-thread-multi / 5.14.1:
  - FAIL http://www.cpantesters.org/cpan/report/c496dcea-6eeb-11ef-98b0-b3c3213a625c

- OpenBSD.amd64-openbsd-thread-multi / 5.14.2:
  - FAIL http://www.cpantesters.org/cpan/report/34f1c456-6e7d-11ef-98b0-b3c3213a625c

**Comment by jonasbn** [comment]
Windows has a single failing test (at the time of writing), see #49

**Comment by timlegge** [comment]
This will likely fix the issues with openbsd but I will need to do some testing:

```
diff --git a/PKCS12.xs b/PKCS12.xs
index 8bbed5f..7a79372 100644
--- a/PKCS12.xs
+++ b/PKCS12.xs
@@ -898,6 +898,7 @@ static int alg_print(pTHX_ BIO *bio, CONST_X509_ALGOR *alg, HV * parameters_hash
                        ASN1_INTEGER_get(kdf->iter), OBJ_nid2sn(prfnid));
       PBKDF2PARAM_free(kdf);
 #if OPENSSL_VERSION_NUMBER > 0x10100000L
+#ifndef LIBRESSL_VERSION_NUMBER
 #ifndef OPENSSL_NO_SCRYPT
       } else if (pbenid == NID_id_scrypt) {
         SCRYPT_PARAMS *kdf = NULL;
@@ -926,6 +927,7 @@ static int alg_print(pTHX_ BIO *bio, CONST_X509_ALGOR *alg, HV * parameters_hash
                        ASN1_INTEGER_get(kdf->parallelizationParameter));
         SCRYPT_PARAMS_free(kdf);
 #endif
+#endif
 #endif
     }
     PBE2PARAM_free(pbe2);
diff --git a/t/pkcs12-info-arbitrary-bag-attributes.t b/t/pkcs12-info-arbitrary-bag-attributes.t
index bccc6ba..76c1df9 100644
--- a/t/pkcs12-info-arbitrary-bag-attributes.t
+++ b/t/pkcs12-info-arbitrary-bag-attributes.t
@@ -2,7 +2,7 @@ use strict;
 use warnings;
 use Test::More;
 use Digest::SHA qw/sha256_hex/;
-use Crypt::OpenSSL::Guess qw/openssl_version/;
+use Crypt::OpenSSL::Guess qw/openssl_version find_openssl_prefix find_openssl_exec/;
 
 my ($major, $minor, $patch) = openssl_version();
 BEGIN { use_ok('Crypt::OpenSSL::PKCS12') };
@@ -123,7 +123,11 @@ if ($major eq '1.0') {
   $openssl_output =~ s/MAC: sha1, Iteration 10000/MAC Iteration 10000/g;
   $openssl_output =~ s/MAC length: .*/MAC verified OK/;
 }
-if ($major ge '3.2') {
+my $prefix = find_openssl_prefix();
+my $ssl_exec = find_openssl_exec($prefix);
+my $ssl_version_string = `$ssl_exec version`;
+
+if ($major ge '3.2' || $ssl_version_string !~ /LibreSSL/) {
   $openssl_output =~ s/2.16.840.1.113894.746875.1.1/Trusted key usage (Oracle)/g;
 }
 
diff --git a/t/pkcs12-info-multiple-pkcs7-sections.t b/t/pkcs12-info-multiple-pkcs7-sections.t
index 8df78e1..99f5e30 100644
--- a/t/pkcs12-info-multiple-pkcs7-sections.t
+++ b/t/pkcs12-info-multiple-pkcs7-sections.t
@@ -2,7 +2,7 @@ use strict;
 use warnings;
 use Test::More;
 use Digest::SHA qw/sha256_hex/;
-use Crypt::OpenSSL::Guess qw/openssl_version/;
+use Crypt::OpenSSL::Guess qw/openssl_version find_openssl_prefix find_openssl_exec/;
 
 my ($major, $minor, $patch) = openssl_version();
 BEGIN { use_ok('Crypt::OpenSSL::PKCS12') };
@@ -76,10 +76,15 @@ if ($major eq '1.0') {
   $openssl_output =~ s/MAC length: .*/MAC verified OK/;
 }
 
+my $prefix = find_openssl_prefix();
+my $ssl_exec = find_openssl_exec($prefix);
+my $ssl_version_string = `$ssl_exec version`;
+
 SKIP: {
 
     skip ("Pre OpenSSL 1.1.0 release does not support utf8 passwords", 20) if ($major le '1.0');
 
+    skip("LibreSSL does not support UTF8 passwords", 15) if ($ssl_version_string =~ /LibreSSL/);
 
 my $pass   = "σύνθημα γνώρισμα";
 my $pkcs12 = Crypt::OpenSSL::PKCS12->new_from_file('certs/shibboleth.pfx');
diff --git a/t/pkcs12-info-secret-bag.t b/t/pkcs12-info-secret-bag.t
index 2e44c56..b9cca4a 100644
--- a/t/pkcs12-info-secret-bag.t
+++ b/t/pkcs12-info-secret-bag.t
@@ -2,7 +2,7 @@ use strict;
 use warnings;
 use Test::More;
 use Digest::SHA qw/sha256_hex/;
-use Crypt::OpenSSL::Guess qw/openssl_version/;
+use Crypt::OpenSSL::Guess qw/openssl_version find_openssl_prefix find_openssl_exec/;
 
 my ($major, $minor, $patch) = openssl_version();
 BEGIN { use_ok('Crypt::OpenSSL::PKCS12') };
@@ -24,9 +24,14 @@ if ($major eq '1.0') {
   $openssl_output =~ s/MAC length: .*/MAC verified OK/;
 }
 
+my $prefix = find_openssl_prefix();
+my $ssl_exec = find_openssl_exec($prefix);
+my $ssl_version_string = `$ssl_exec version`;
+
 SKIP: {
 
     skip ("Pre OpenSSL 3.0.0 release secret bags unsupported", 22) if ($major lt '3.0');
+    skip ("LibreSSL does not support secret bags", 22) if ($ssl_version_string =~ /LibreSSL/);
 
 my $pass   = "Password1";
 my $pkcs12 = Crypt::OpenSSL::PKCS12->new_from_file('certs/secretbag.p12');

```
