### ISSUE TITLE
Investigate reports on failing tests from CPAN testers; 1.92 (Windows)

### ISSUE THREAD

**Issue by jonasbn** [dsully/perl-crypt-openssl-pkcs12#49]
Investigate reports on failing tests from CPAN testers. Windows issue:

Crypt-OpenSSL-PKCS12-1.92:

- MSWin32-x64-multi-thread / 5.40.0:
  - FAIL http://www.cpantesters.org/cpan/report/ffa00e1e-6dd8-1014-9fa9-da9af891d987 

OpenBSD has a lot of reports on failing tests, see: #48

**Comment by timlegge** [comment]
Same issue as #50 windows does not seem to have the legacy provider.  The fix is likely the same
